POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "email": "em@qw2s10.ff",
  "password": "1"
}

###
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "em@qw2s.ff",
  "password": "eef33f3f"
}

###
